### ISSUE TITLE
程序停止运行

### ISSUE THREAD

**Issue by sunhaochen0** [j2rong/FakeLocation#102]
Hardware: kirin710, AGS3-W00E
Device: HUAWEI, HUAWEI, AGS3-W00E
ROM: AGS3-W00E 10.1.0.160(C00E137R1P133)
Android Version: SDK: 10 (sdk:29)

Locale: zh_CN_#Hans
Date: Thu May 20 13:51:45 GMT+08:00 2021
Channel: chKuAn
App Version: 1.2.681.1701(681)

android.util.AndroidRuntimeException: Unknown error code -1 when starting Intent { act=de.robv.android.xposed.installer.OPEN_SECTION flg=0x10000000 pkg=de.robv.android.xposed.installer (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2150)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1746)
	at android.app.Activity.startActivityForResult(Activity.java:5362)
	at android.support.v4.app.j.startActivityForResult(Unknown Source:10)
	at android.support.v4.app.l.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivityForResult(Activity.java:5303)
	at android.support.v4.app.l.startActivityForResult(Unknown Source:10)
	at android.app.Activity.startActivity(Activity.java:5733)
	at android.app.Activity.startActivity(Activity.java:5701)
	at com.rong.xposed.fakelocation.ui.MainActivity$4.onClick(Unknown Source:38)
	at android.support.v7.app.AlertController$b.handleMessage(Unknown Source:20)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by 15687702323** [comment]
手机系统最好是安卓7的
