### ISSUE TITLE
ActivityNotFoundException if using material design xposed installer

### ISSUE THREAD

**Issue by liwanglin12** [j2rong/FakeLocation#11]
Hardware: qcom, gemini
Device: Xiaomi, Xiaomi, MI 5
ROM: MXB48T
Android Version: SDK: 6.0.1 (sdk:23)

Locale: zh_CN
Date: Thu Jul 14 19:45:58 GMT+08:00 2016
App Version: 0.7.306.574(306)

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=de.robv.android.xposed.installer.OPEN_SECTION flg=0x10000000 pkg=de.robv.android.xposed.installer (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1514)
	at android.app.Activity.startActivityForResult(Activity.java:3993)
	at android.app.Activity.startActivityForResult(Activity.java:3954)
	at android.support.v4.app.aa.startActivityForResult(Unknown Source)
	at android.app.Activity.startActivity(Activity.java:4277)
	at android.app.Activity.startActivity(Activity.java:4245)
	at com.rong.xposed.fakelocation.i.onClick(Unknown Source)
	at android.support.v7.a.q.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5462)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:163)

**Comment by j2rong** [comment]
使用的是官方版本的Xposed Installer？

**Comment by liwanglin12** [comment]
是

2016年8月4日 上午12:33，"j2rong" <notifications@github.com>写道：

**Comment by j2rong** [comment]
fix in 0.9
