### ISSUE TITLE
无法定位

### ISSUE THREAD

**Issue by hello-earth** [j2rong/FakeLocation#12]
-----------------
2016年7月14日 PM1:07:17 UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'KOT49H.I9500ZCUHNF1' with fingerprint 'samsung/ja3gzc/ja3g:4.4.2/KOT49H/I9500ZCUHNF1:user/release-keys'
Loading modules from /data/app/com.rong.xposed.fakelocation-1.apk
  Loading class com.rong.xposed.fakelocation.XFakeLocation
[XFL initZygote] log status = false
-----------------
2016年7月14日 PM1:11:45 UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'KOT49H.I9500ZCUHNF1' with fingerprint 'samsung/ja3gzc/ja3g:4.4.2/KOT49H/I9500ZCUHNF1:user/release-keys'
Loading modules from /data/app/com.rong.xposed.fakelocation-1.apk
  Loading class com.rong.xposed.fakelocation.XFakeLocation
[XFL initZygote] log status = false
java.lang.NoSuchMethodError: android.location.GpsStatus#setStatus(java.lang.Integer,int[],float[],float[],float[],java.lang.Integer,java.lang.Integer,java.lang.Integer)#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:271)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:284)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:947)
	at com.rong.xposed.fakelocation.x.b.e.b(Unknown Source)
	at com.rong.xposed.fakelocation.x.c.afterHookedMethod(Unknown Source)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.location.LocationManager.getGpsStatus(Native Method)
	at com.nianticlabs.nia.location.LocationManagerProvider$2.onGpsStatusChanged(LocationManagerProvider.java:155)
	at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1468)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.os.HandlerThread.run(HandlerThread.java:61)
java.lang.NoSuchMethodError: android.location.GpsStatus#setStatus(java.lang.Integer,int[],float[],float[],float[],java.lang.Integer,java.lang.Integer,java.lang.Integer)#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:233)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:284)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:947)
	at com.rong.xposed.fakelocation.x.b.e.b(Unknown Source)
	at com.rong.xposed.fakelocation.x.c.afterHookedMethod(Unknown Source)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.location.LocationManager.getGpsStatus(Native Method)
	at com.nianticlabs.nia.location.LocationManagerProvider$2.onGpsStatusChanged(LocationManagerProvider.java:155)
	at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1468)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.os.HandlerThread.run(HandlerThread.java:61)
java.lang.NoSuchMethodError: android.location.GpsStatus#setStatus(java.lang.Integer,int[],float[],float[],float[],java.lang.Integer,java.lang.Integer,java.lang.Integer)#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:233)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:284)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:947)
	at com.rong.xposed.fakelocation.x.b.e.b(Unknown Source)
	at com.rong.xposed.fakelocation.x.c.afterHookedMethod(Unknown Source)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.location.LocationManager.getGpsStatus(Native Method)
	at com.nianticlabs.nia.location.LocationManagerProvider$2.onGpsStatusChanged(LocationManagerProvider.java:155)
	at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1468)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.os.HandlerThread.run(HandlerThread.java:61)
java.lang.NoSuchMethodError: android.location.GpsStatus#setStatus(java.lang.Integer,int[],float[],float[],float[],java.lang.Integer,java.lang.Integer,java.lang.Integer)#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:233)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:284)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:947)
	at com.rong.xposed.fakelocation.x.b.e.b(Unknown Source)
	at com.rong.xposed.fakelocation.x.c.afterHookedMethod(Unknown Source)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.location.LocationManager.getGpsStatus(Native Method)
	at com.nianticlabs.nia.location.LocationManagerProvider$2.onGpsStatusChanged(LocationManagerProvider.java:155)
	at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1468)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.os.HandlerThread.run(HandlerThread.java:61)
java.lang.NoSuchMethodError: android.location.GpsStatus#setStatus(java.lang.Integer,int[],float[],float[],float[],java.lang.Integer,java.lang.Integer,java.lang.Integer)#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:233)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:284)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:947)
	at com.rong.xposed.fakelocation.x.b.e.b(Unknown Source)
	at com.rong.xposed.fakelocation.x.c.afterHookedMethod(Unknown Source)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.location.LocationManager.getGpsStatus(Native Method)
	at com.nianticlabs.nia.location.LocationManagerProvider$2.onGpsStatusChanged(LocationManagerProvider.java:155)
	at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1468)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.os.HandlerThread.run(HandlerThread.java:61)
java.lang.NoSuchMethodError: android.location.GpsStatus#setStatus(java.lang.Integer,int[],float[],float[],float[],java.lang.Integer,java.lang.Integer,java.lang.Integer)#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:233)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:284)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:947)
	at com.rong.xposed.fakelocation.x.b.e.b(Unknown Source)
	at com.rong.xposed.fakelocation.x.c.afterHookedMethod(Unknown Source)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.location.LocationManager.getGpsStatus(Native Method)
	at com.nianticlabs.nia.location.LocationManagerProvider$2.onGpsStatusChanged(LocationManagerProvider.java:155)
	at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1468)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.os.HandlerThread.run(HandlerThread.java:61)
java.lang.NoSuchMethodError: android.location.GpsStatus#setStatus(java.lang.Integer,int[],float[],float[],float[],java.lang.Integer,java.lang.Integer,java.lang.Integer)#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:233)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:284)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:947)
	at com.rong.xposed.fakelocation.x.b.e.b(Unknown Source)
	at com.rong.xposed.fakelocation.x.c.afterHookedMethod(Unknown Source)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.location.LocationManager.getGpsStatus(Native Method)
	at com.nianticlabs.nia.location.LocationManagerProvider$2.onGpsStatusChanged(LocationManagerProvider.java:155)
	at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1468)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.os.HandlerThread.run(HandlerThread.java:61)
java.lang.NoSuchMethodError: android.location.GpsStatus#setStatus(java.lang.Integer,int[],float[],float[],float[],java.lang.Integer,java.lang.Integer,java.lang.Integer)#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:233)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:284)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:947)
	at com.rong.xposed.fakelocation.x.b.e.b(Unknown Source)
	at com.rong.xposed.fakelocation.x.c.afterHookedMethod(Unknown Source)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.location.LocationManager.getGpsStatus(Native Method)
	at com.nianticlabs.nia.location.LocationManagerProvider$2.onGpsStatusChanged(LocationManagerProvider.java:155)
	at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1468)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.os.HandlerThread.run(HandlerThread.java:61)
java.lang.NoSuchMethodError: android.location.GpsStatus#setStatus(java.lang.Integer,int[],float[],float[],float[],java.lang.Integer,java.lang.Integer,java.lang.Integer)#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:233)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:284)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:947)
	at com.rong.xposed.fakelocation.x.b.e.b(Unknown Source)
	at com.rong.xposed.fakelocation.x.c.afterHookedMethod(Unknown Source)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.location.LocationManager.getGpsStatus(Native Method)
	at com.nianticlabs.nia.location.LocationManagerProvider$2.onGpsStatusChanged(LocationManagerProvider.java:155)
	at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1468)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.os.HandlerThread.run(HandlerThread.java:61)
java.lang.NoSuchMethodError: android.location.GpsStatus#setStatus(java.lang.Integer,int[],float[],float[],float[],java.lang.Integer,java.lang.Integer,java.lang.Integer)#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:233)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:284)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:947)
	at com.rong.xposed.fakelocation.x.b.e.b(Unknown Source)
	at com.rong.xposed.fakelocation.x.c.afterHookedMethod(Unknown Source)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.location.LocationManager.getGpsStatus(Native Method)
	at com.nianticlabs.nia.location.LocationManagerProvider$2.onGpsStatusChanged(LocationManagerProvider.java:155)
	at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1468)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.os.HandlerThread.run(HandlerThread.java:61)
java.lang.NoSuchMethodError: android.location.GpsStatus#setStatus(java.lang.Integer,int[],float[],float[],float[],java.lang.Integer,java.lang.Integer,java.lang.Integer)#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:233)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:284)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:947)
	at com.rong.xposed.fakelocation.x.b.e.b(Unknown Source)
	at com.rong.xposed.fakelocation.x.c.afterHookedMethod(Unknown Source)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.location.LocationManager.getGpsStatus(Native Method)
	at com.nianticlabs.nia.location.LocationManagerProvider$2.onGpsStatusChanged(LocationManagerProvider.java:155)
	at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1468)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.os.HandlerThread.run(HandlerThread.java:61)
java.lang.NoSuchMethodError: android.location.GpsStatus#setStatus(java.lang.Integer,int[],float[],float[],float[],java.lang.Integer,java.lang.Integer,java.lang.Integer)#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:233)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:284)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:947)
	at com.rong.xposed.fakelocation.x.b.e.b(Unknown Source)
	at com.rong.xposed.fakelocation.x.c.afterHookedMethod(Unknown Source)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.location.LocationManager.getGpsStatus(Native Method)
	at com.nianticlabs.nia.location.LocationManagerProvider$2.onGpsStatusChanged(LocationManagerProvider.java:155)
	at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1468)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.os.HandlerThread.run(HandlerThread.java:61)
java.lang.NoSuchMethodError: android.location.GpsStatus#setStatus(java.lang.Integer,int[],float[],float[],float[],java.lang.Integer,java.lang.Integer,java.lang.Integer)#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:233)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:284)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:947)
	at com.rong.xposed.fakelocation.x.b.e.b(Unknown Source)
	at com.rong.xposed.fakelocation.x.c.afterHookedMethod(Unknown Source)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.location.LocationManager.getGpsStatus(Native Method)
	at com.nianticlabs.nia.location.LocationManagerProvider$2.onGpsStatusChanged(LocationManagerProvider.java:155)
	at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1468)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.os.HandlerThread.run(HandlerThread.java:61)
java.lang.NoSuchMethodError: android.location.GpsStatus#setStatus(java.lang.Integer,int[],float[],float[],float[],java.lang.Integer,java.lang.Integer,java.lang.Integer)#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:233)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:284)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:947)
	at com.rong.xposed.fakelocation.x.b.e.b(Unknown Source)
	at com.rong.xposed.fakelocation.x.c.afterHookedMethod(Unknown Source)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.location.LocationManager.getGpsStatus(Native Method)
	at com.nianticlabs.nia.location.LocationManagerProvider$2.onGpsStatusChanged(LocationManagerProvider.java:155)
	at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1468)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.os.HandlerThread.run(HandlerThread.java:61)
java.lang.NoSuchMethodError: android.location.GpsStatus#setStatus(java.lang.Integer,int[],float[],float[],float[],java.lang.Integer,java.lang.Integer,java.lang.Integer)#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:233)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:284)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:947)
	at com.rong.xposed.fakelocation.x.b.e.b(Unknown Source)
	at com.rong.xposed.fakelocation.x.c.afterHookedMethod(Unknown Source)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.location.LocationManager.getGpsStatus(Native Method)
	at com.nianticlabs.nia.location.LocationManagerProvider$2.onGpsStatusChanged(LocationManagerProvider.java:155)
	at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1468)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by j2rong** [comment]
Turn on GMS hook on advanced settings and hook google play service 
http://www.coolapk.com/apk/com.rong.xposed.fakelocation
