### ISSUE TITLE
android.content.ActivityNotFoundException: No Activity found to handle Intent

### ISSUE THREAD

**Issue by javibcit** [j2rong/FakeLocation#15]
Hardware: mt6582, luv80ds_global_com
Device: LGE, lge, LG-D335E
ROM: ALPS.KK1.AOSP.MP2.TC1SP.V1.19
Android Ve

Locale: es_ES
Date: Wed Aug 03 21:40:29 CEST 2016
Channel: chXposedRepo
App Version: 0.8.404.813(404)

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=de.robv.android.xposed.installer.OPEN_SECTION flg=0x10000000 pkg=de.robv.android.xposed.installer (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
	at android.app.Activity.startActivityForResult(Activity.java:3468)
	at android.app.Activity.startActivityForResult(Activity.java:3429)
	at android.support.v4.app.aa.startActivityForResult(Unknown Source)
	at android.app.Activity.startActivity(Activity.java:3671)
	at android.app.Activity.startActivity(Activity.java:3639)
	at com.rong.xposed.fakelocation.i.onClick(Unknown Source)
	at android.support.v7.a.q.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5118)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by j2rong** [comment]
#11 
u can active the module manually for now

**Comment by j2rong** [comment]
fix in 0.9
