### ISSUE TITLE
所有软件都不能定位。。还有实时运动功能也不行。

### ISSUE THREAD

**Issue by lsh93** [j2rong/FakeLocation#42]
日志为空01-15 16:24:43.415 I/Xposed  (12606): [LM:agsl] com.yuedong.sport {addGpsStatusListener}
01-15 16:24:43.416 I/Xposed  (12606): [LM:rlu] com.yuedong.sport {creating proxy}
01-15 16:24:43.423 I/Xposed  (12606): [LM:rlu] com.yuedong.sport {listener, la=22.528225, lo=114.051307, b=31.90, s=6.00}
01-15 16:24:43.424 I/Xposed  (12606): [LM:XLL:olc] com.yuedong.sport {gps, la=22.528225, lo=114.051307, b=31.90, s=6.00}
01-15 16:24:43.424 I/Xposed  (12606): [LM:rlu] com.yuedong.sport {creating proxy}
01-15 16:24:43.429 I/Xposed  (12606): [LM:rlu] com.yuedong.sport {listener, la=22.528225, lo=114.051307, b=31.90, s=6.00}
01-15 16:24:43.430 I/Xposed  (12606): [LM:XLL:olc] com.yuedong.sport {gps, la=22.528225, lo=114.051307, b=31.90, s=6.00}
01-15 16:24:43.430 I/Xposed  (12606): [LM:anl] com.yuedong.sport {status=on}
01-15 16:24:43.431 I/Xposed  (12606): [TM:gaci] com.yuedong.sport {gps=on}
01-15 16:24:43.431 I/Xposed  (12606): [TM:gcl] com.yuedong.sport {status(gps)=on}
01-15 16:24:43.432 I/Xposed  (12606): [WM:gsr] com.yuedong.sport {on, wifi}
01-15 16:24:43.432 I/Xposed  (12606): [TM:gaci] com.yuedong.sport {gps=on}
01-15 16:24:43.432 I/Xposed  (12606): [TM:gcl] com.yuedong.sport {status(gps)=on}
01-15 16:24:43.445 I/Xposed  (12606): [TM:gaci] com.yuedong.sport {gps=on}
01-15 16:24:43.445 I/Xposed  (12606): [TM:gnci] com.yuedong.sport {gps=on}
01-15 16:24:43.445 I/Xposed  (12606): [TM:gaci] com.yuedong.sport {gps=on}
01-15 16:24:43.446 I/Xposed  (12606): [TM:gcl] com.yuedong.sport {status(gps)=on}
01-15 16:24:43.446 I/Xposed  (12606): [WM:gsr] com.yuedong.sport {on, wifi}
01-15 16:24:43.448 I/Xposed  (12606): [TM:gaci] com.yuedong.sport {gps=on}
01-15 16:24:43.448 I/Xposed  (12606): [TM:gcl] com.yuedong.sport {status(gps)=on}
01-15 16:24:44.680 I/Xposed  (12606): [LM:ipe] com.yuedong.sport {p=gps, gps, true}
01-15 16:24:47.463 I/Xposed  (12606): [WM:gsr] com.yuedong.sport {on, wifi}
01-15 16:24:47.463 I/Xposed  (12606): [TM:gaci] com.yuedong.sport {gps=on}
01-15 16:24:47.463 I/Xposed  (12606): [TM:gcl] com.yuedong.sport {status(gps)=on}
01-15 16:24:49.388 I/Xposed  (12606): [TM:gaci] com.yuedong.sport {gps=on}
01-15 16:24:49.388 I/Xposed  (12606): [TM:gcl] com.yuedong.sport {status(gps)=on}
01-15 16:24:52.389 I/Xposed  (12606): [TM:gaci] com.yuedong.sport {gps=on}
01-15 16:24:52.390 I/Xposed  (12606): [TM:gcl] com.yuedong.sport {status(gps)=on}
01-15 16:24:55.392 I/Xposed  (12606): [TM:gaci] com.yuedong.sport {gps=on}
01-15 16:24:55.392 I/Xposed  (12606): [TM:gcl] com.yuedong.sport {status(gps)=on}
01-15 16:24:55.393 I/Xposed  (12606): [WM:gsr] com.yuedong.sport {on, wifi}
01-15 16:24:59.495 I/Xposed  (12606): [WM:gsr] com.yuedong.sport {on, wifi}
01-15 16:24:59.495 I/Xposed  (12606): [TM:gaci] com.yuedong.sport {gps=on}
01-15 16:24:59.496 I/Xposed  (12606): [TM:gcl] com.yuedong.sport {status(gps)=on}
01-15 16:24:59.496 I/Xposed  (12606): [WM:gsr] com.yuedong.sport {on, wifi}
01-15 16:25:01.390 I/Xposed  (12606): [TM:gaci] com.yuedong.sport {gps=on}
01-15 16:25:01.391 I/Xposed  (12606): [TM:gcl] com.yuedong.sport {status(gps)=on}
01-15 16:25:01.391 I/Xposed  (12606): [WM:gsr] com.yuedong.sport {on, wifi}
01-15 16:25:01.866 E/Xposed  (12606): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
01-15 16:25:01.866 E/Xposed  (12606): 	at com.specher.sm.HookSensor$1.afterHookedMethod(HookSensor.java:111)
01-15 16:25:01.866 E/Xposed  (12606): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
01-15 16:25:01.866 E/Xposed  (12606): 	at android.hardware.SensorManager.getSensorList(<Xposed>)
01-15 16:25:01.866 E/Xposed  (12606): 	at android.hardware.SensorManager.getDefaultSensor(SensorManager.java:449)
01-15 16:25:01.866 E/Xposed  (12606): 	at com.yuedong.stepdetector.StepDetector.start(SourceFile:226)
01-15 16:25:01.866 E/Xposed  (12606): 	at com.yuedong.sport.controller.stepdetect.StepDetectorEngine.startSoftDetector(SourceFile:84)
01-15 16:25:01.866 E/Xposed  (12606): 	at com.yuedong.sport.controller.stepdetect.StepDetectorEngine.startDetect(SourceFile:198)
01-15 16:25:01.866 E/Xposed  (12606): 	at com.yuedong.sport.controller.stepdetect.StepDetectorEngine.start(SourceFile:107)
01-15 16:25:01.866 E/Xposed  (12606): 	at com.yuedong.sport.controller.stepdetect.ServiceAutoStep.k(SourceFile:529)
01-15 16:25:01.866 E/Xposed  (12606): 	at com.yuedong.sport.controller.stepdetect.ServiceAutoStep.onStartCommand(SourceFile:371)
01-15 16:25:01.866 E/Xposed  (12606): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3017)
01-15 16:25:01.866 E/Xposed  (12606): 	at android.app.ActivityThread.access$2200(ActivityThread.java:153)
01-15 16:25:01.866 E/Xposed  (12606): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
01-15 16:25:01.866 E/Xposed  (12606): 	at org.acdd.hack.AndroidHack$HandlerHack.handleMessage(SourceFile:201)
01-15 16:25:01.866 E/Xposed  (12606): 	at android.os.Handler.dispatchMessage(Handler.java:98)
01-15 16:25:01.866 E/Xposed  (12606): 	at android.os.Looper.loop(Looper.java:148)
01-15 16:25:01.866 E/Xposed  (12606): 	at android.app.ActivityThread.main(ActivityThread.java:5441)
01-15 16:25:01.866 E/Xposed  (12606): 	at java.lang.reflect.Method.invoke(Native Method)
01-15 16:25:01.866 E/Xposed  (12606): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
01-15 16:25:01.866 E/Xposed  (12606): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
01-15 16:25:01.866 E/Xposed  (12606): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
01-15 16:25:01.907 I/Xposed  (12606): getSensorList：19获取到的传感器信息：[{Sensor name="Step Counter", vendor="QTI", version=2, type=19, maxRange=1.0, resolution=1.0, power=0.8999939, minDelay=0}, {Sensor name="Step Counter -Wakeup Secondary", vendor="QTI", version=2, type=19, maxRange=1.0, resolution=1.0, power=0.8999939, minDelay=0}]
01-15 16:25:01.929 I/Xposed  (12606): [LM:ru] com.yuedong.sport {remove proxy}
01-15 16:25:01.956 I/Xposed  (12606): [LM:ru] com.yuedong.sport {remove proxy}
01-15 16:25:03.539 I/Xposed  (12606): 传感器为NULL

**Comment by j2rong** [comment]
目前没有传感器模拟功能。日志中的错误是由`HookSensor`造成的。
如无法定位可尝试使用上个版本看看
