### ISSUE TITLE
App is Crashing when I select any app. 

### ISSUE THREAD

**Issue by sapthesh** [j2rong/FakeLocation#5]
Hardware: mt6582, MACHFIVE
Device: Karbonn, Karbonn, MACHFIVE
ROM: KARBONN_MACHFIVE_L104_23072015
Android Version: SDK: 5.0 (sdk:21)

Locale: en_US
Date: Tue Jul 12 18:05:53 GMT+05:30 2016
App Version: 0.7.300.564(300)

java.lang.ClassCastException: android.text.SpannableString cannot be cast to java.lang.String
	at com.rong.xposed.fakelocation.a.e.onClick(Unknown Source)
	at android.view.View.performClick(View.java:4802)
	at android.view.View$PerformClick.run(View.java:20101)
	at android.os.Handler.handleCallback(Handler.java:810)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:189)
	at android.app.ActivityThread.main(ActivityThread.java:5529)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

CrashLog

**Comment by j2rong** [comment]
fix in v0.7.306
