### ISSUE TITLE
MIUI9 显示不出悬浮窗

### ISSUE THREAD

**Issue by ncs19960831** [j2rong/FakeLocation#64]
手机小米5 系统MIUI9 使用期间都没有问题，但是尝试打开悬浮窗出现问题。根据提示打开了悬浮窗权限并且重启依然不会显示。有一定几率闪一下就会消失

**Comment by ncs19960831** [comment]
我很想输出一个log，但是我在installer里面找不到log输出

**Comment by ncs19960831** [comment]
终于输出了log
我换了系统，现在系统为lineageos
Hardware: qcom, gemini
Device: Xiaomi, Xiaomi, MI 5
ROM: lineage_gemini-userdebug 7.1.2 NJH47F 278f874f2f
Android Version: SDK: 7.1.2 (sdk:25)

Locale: zh_CN
Date: Sun Feb 25 15:53:33 GMT+08:00 2018
Channel: chXposedRepo
App Version: 1.2.681.1701(681)


android.view.WindowManager$BadTokenException: Unable to add window -- window android.view.ViewRootImpl$W@8743dde has already been added
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:691)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
	at com.rong.xposed.fakelocation.service.f.FxService.m(Unknown Source)
	at com.rong.xposed.fakelocation.service.f.FxService.a(Unknown Source)
	at com.rong.xposed.fakelocation.service.f.widget.s.a(Unknown Source)
	at com.rong.xposed.fakelocation.service.f.widget.s.c(Unknown Source)
	at com.rong.xposed.fakelocation.service.f.widget.s.onTouchEvent(Unknown Source)
	at android.view.View.dispatchTouchEvent(View.java:10024)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
	at android.view.View.dispatchTouchEvent(<Xposed>)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2626)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
	at android.view.View.dispatchPointerEvent(View.java:10244)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPoi
