### ISSUE TITLE
小米6sagit魔趣71.2闪退

### ISSUE THREAD

**Issue by kingfanslwh** [j2rong/FakeLocation#66]
Hardware: qcom, mk_sagit
Device: Xiaomi, Xiaomi, MI 6
ROM: mk_sagit-userdebug 7.1.2 NJH47F 85cf8b2d03 test-keys
Android Version: SDK: 7.1.2 (sdk:25)

Locale: zh_CN
Date: Tue Nov 21 09:22:19 GMT+08:00 2017
Channel: chXposedRepo
App Version: 1.2.681.1701(681)

android.view.WindowManager$BadTokenException: Unable to add window -- window android.view.ViewRootImpl$W@5334139 has already been added
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:691)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
	at android.view.WindowManagerGlobal.addView(<Xposed>)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
	at com.rong.xposed.fakelocation.service.f.FxService.l(Unknown Source)
	at com.rong.xposed.fakelocation.service.f.FxService.k(Unknown Source)
	at com.rong.xposed.fakelocation.service.f.FxService$a$1.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by JasonPhone** [comment]
Hardware: qcom, mk_sagit
Device: Xiaomi, Xiaomi, MI 6
ROM: mk_sagit-userdebug 7.1.2 NJH47F f43b836616 test-keys
Android Version: SDK: 7.1.2 (sdk:25)

Locale: zh_CN
Date: Sun May 20 12:26:44 GMT+08:00 2018
Channel: chKuAn
App Version: 1.2.681.1701(681)


android.view.WindowManager$BadTokenException: Unable to add window -- window android.view.ViewRootImpl$W@609d9e6 has already been added
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:691)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
	at com.rong.xposed.fakelocation.service.f.FxService.m(Unknown Source)
	at com.rong.xposed.fakelocation.service.f.FxService.a(Unknown Source)
	at com.rong.xposed.fakelocation.service.f.widget.s.a(Unknown Source)
	at com.rong.xposed.fakelocation.service.f.widget.s.c(Unknown Source)
	at com.rong.xposed.fakelocation.service.f.widget.s.onTouchEvent(Unknown Source)
	at android.view.View.dispatchTouchEvent(View.java:10024)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2626)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
	at android.view.View.dispatchPointerEvent(View.java:10244)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4444)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4312)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4005)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4062)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6253)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6227)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6188)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6356)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
// 悬浮窗功能下崩溃
// 小米6 魔趣sagit稳定版 Android7.1.2
